// Center column panel states
export const DISPLAY_DEFAULT = 'DISPLAY_DEFAULT';
export const DISPLAY_LOGIN = 'DISPLAY_LOGIN';
export const DISPLAY_CREATE_ACCOUNT = 'DISPLAY_CREATE_ACCOUNT';
export const DISPLAY_MENU_VIEWING = 'DISPLAY_MENU_VIEWING';
export const DISPLAY_MENU_ORDERING = 'DISPLAY_MENU_ORDERING';
export const DISPLAY_NEW_ORDER_OPTIONS = 'DISPLAY_NEW_ORDER_OPTIONS';
export const DISPLAY_SUGGEST_OPTIONS = 'DISPLAY_SUGGEST_OPTIONS';
