export const REQUEST_RESTAURANTS = 'REQUEST_RESTAURANTS';
export const RECEIVE_RESTAURANTS = 'RECEIVE_RESTAURANTS';
export const UPDATE_RESTAURANT_HOURS = 'UPDATE_RESTAURANT_HOURS';

export const REQUEST_PENDING_ORDERS = 'REQUEST_PENDING_ORDERS';
export const RECEIVE_PENDING_ORDERS = 'RECEIVE_PENDING_ORDERS';

export const REQUEST_ACTIVE_ORDERS = 'REQUEST_ACTIVE_ORDERS';
export const RECEIVE_ACTIVE_ORDERS = 'RECEIVE_ACTIVE_ORDERS';

export const REQUEST_ORGANIZED_ORDERS = 'REQUEST_ORGANIZED_ORDERS';
export const RECEIVE_ORGANIZED_ORDERS = 'RECEIVE_ORGANIZED_ORDERS';

export const REQUEST_MY_ORDERS = 'REQUEST_MY_ORDERS';
export const RECEIVE_MY_ORDERS = 'RECEIVE_MY_ORDERS';

export const REQUEST_MENU = 'REQUEST_MENU';
export const RECEIVE_MENU = 'RECEIVE_MENU';

export const REQUEST_VOTES = 'REQUEST_VOTES';
export const RECEIVE_VOTES = 'RECEIVE_VOTES';

export const REQUEST_NUM_ORDERS = 'REQUEST_NUM_ORDERS';
export const RECEIVE_NUM_ORDERS = 'RECEIVE_NUM_ORDERS';

export const SHOW_MENU = 'SHOW_MENU';
export const HIDE_MENU = 'HIDE_MENU';

export const START_ORDER = 'START_ORDER';
export const JOIN_ORDER = 'JOIN_ORDER';
export const ACTIVATE_ORDER = 'ACTIVATE_ORDER';
export const ADD_ITEM_TO_ORDER = 'ADD_ITEM_TO_ORDER';
export const REMOVE_ITEM_FROM_ORDER = 'REMOVE_ITEM_FROM_ORDER';
export const INCREMENT_ITEM = 'INCREMENT_ITEM';
export const DECREMENT_ITEM = 'DECREMENT_ITEM';
export const SET_QUANTITY = 'SET_QUANTITY';

export const CONTINUE_ORDER = 'CONTINUE_ORDER';
export const GO_BACK_TO_MENU = 'GO_BACK_TO_MENU';
export const SET_ORDER_TYPE = 'SET_ORDER_TYPE';
export const SET_ORDER_DURATION = 'SET_ORDER_DURATION';

export const SEND_NEW_GROUP = 'SEND_NEW_GROUP';
export const NEW_GROUP_SUCCESS = 'NEW_GROUP_SUCCESS';
export const NEW_GROUP_FAILURE = 'NEW_GROUP_FAILURE';

export const SEND_NEW_ORDER = 'SEND_NEW_ORDER';
export const NEW_ORDER_SUCCESS = 'NEW_ORDER_SUCCESS';
export const NEW_ORDER_FAILURE = 'NEW_ORDER_FAILURE';

export const SEND_ACTIVATED_GROUP = 'SEND_ACTIVATED_GROUP';
export const ACTIVATED_GROUP_SUCCESS = 'ACTIVATED_GROUP_SUCCESS';
export const ACTIVATED_GROUP_FAILURE = 'ACTIVATED_GROUP_FAILURE';

export const SHOW_SUGGESTION = 'SHOW_SUGGESTION';
export const HIDE_SUGGESTION = 'HIDE_SUGGESTION';
export const TOGGLE_DELIVERY = 'TOGGLE_DELIVERY';
export const TOGGLE_CARRYOUT = 'TOGGLE_CARRYOUT';
export const TOGGLE_OUTING = 'TOGGLE_OUTING';
export const SET_DRIVING_PREFERENCE = 'SET_DRIVING_PREFERENCE';
export const SET_WAIT_TIME = 'SET_WAIT_TIME';
export const SET_MIN_PEOPLE = 'SET_MIN_PEOPLE';

export const SEND_SUGGESTION = 'SEND_SUGGESTION';
export const SUGGESTION_SUCCESS = 'SUGGESTION_SUCCESS';
export const SUGGESTION_FAILURE = 'SUGGESTION_FAILURE';

export const SEND_LOGIN = 'SEND_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const PROMPT_LOGIN = 'PROMPT_LOGIN';
export const UPDATE_USERNAME_FIELD = 'CHANGE_USERNAME_FIELD';
export const UPDATE_PASSWORD_FIELD = 'UPDATE_PASSWORD_FIELD';
export const UPDATE_CONFIRM_PASSWORD_FIELD = 'UPDATE_CONFIRM_PASSWORD_FIELD';

export const SET_USER_INFO = 'SET_USER_INFO';
export const LOG_OUT = 'LOG_OUT';

export const GOTO_CREATE_ACCOUNT = 'GOTO_CREATE_ACCOUNT';
export const GOTO_LOGIN = 'GOTO_LOGIN';

export const SEND_NEW_ACCOUNT = 'SEND_NEW_USER';
export const NEW_ACCOUNT_SUCCESS = 'NEW_USER_SUCCESS';
export const NEW_ACCOUNT_FAILURE = 'NEW_USER_FAILURE';

export const OPEN_PIZZA_BUILDER = 'OPEN_PIZZA_BUILDER';
export const CLOSE_PIZZA_BUILDER = 'CLOSE_PIZZA_BUILDER';
export const SET_PIZZA_SIZE = 'SET_PIZZA_SIZE';
export const TOGGLE_TOPPING = 'TOGGLE_TOPPING';
export const CHANGE_TOPPING_SIDE = 'CHANGE_TOPPING_SIDE';
export const SET_INITIAL_SAUCE = 'SET_INITIAL_SAUCE';
export const SET_MAX_TOPPINGS = 'SET_MAX_TOPPINGS';
export const CHANGE_SAUCE = 'CHANGE_SAUCE';
export const CHANGE_CHEESE = 'CHANGE_CHEESE';

export const SHOW_GROUP_DETAILS = 'SHOW_GROUP_DETAILS';
export const HIDE_GROUP_DETAILS = 'HIDE_GROUP_DETAILS';

export const RECEIVE_USERNAME = 'RECEIVE_USERNAME';

export const SHOW_ORDER_DETAILS = 'SHOW_ORDER_DETAILS';
export const HIDE_ORDER_DETAILS = 'HIDE_ORDER_DETAILS';
