export const REQUEST_RESTAURANTS = 'REQUEST_RESTAURANTS';
export const RECEIVE_RESTAURANTS = 'RECEIVE_RESTAURANTS';
export const UPDATE_RESTAURANT_HOURS = 'UPDATE_RESTAURANT_HOURS';

export const REQUEST_PENDING_ORDERS = 'REQUEST_PENDING_ORDERS';
export const RECEIVE_PENDING_ORDERS = 'RECEIVE_PENDING_ORDERS';

export const REQUEST_ACTIVE_ORDERS = 'REQUEST_ACTIVE_ORDERS';
export const RECEIVE_ACTIVE_ORDERS = 'RECEIVE_ACTIVE_ORDERS';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const REQUEST_MENU = 'REQUEST_MENU';
export const RECEIVE_MENU = 'RECEIVE_MENU';

export const SHOW_MENU = 'SHOW_MENU';
export const HIDE_MENU = 'HIDE_MENU';

export const START_ORDER = 'START_ORDER';
export const ADD_ITEM_TO_ORDER = 'ADD_ITEM_TO_ORDER';
export const REMOVE_ITEM_FROM_ORDER = 'REMOVE_ITEM_FROM_ORDER';
export const INCREMENT_ITEM = 'INCREMENT_ITEM';
export const DECREMENT_ITEM = 'DECREMENT_ITEM';
export const SET_QUANTITY = 'SET_QUANTITY';

export const SHOW_SUGGESTION = 'SHOW_SUGGESTION';
export const HIDE_SUGGESTION = 'HIDE_SUGGESTION';
export const TOGGLE_DELIVERY = 'TOGGLE_DELIVERY';
export const TOGGLE_CARRYOUT = 'TOGGLE_CARRYOUT';
export const TOGGLE_OUTING = 'TOGGLE_OUTING';
export const SET_DRIVING_PREFERENCE = 'SET_DRIVING_PREFERENCE';
export const SET_WAIT_TIME = 'SET_WAIT_TIME';
